# Generated by Django 5.0.6 on 2024-06-25 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commneted_by',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_on',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='commented_on',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='image',
        ),
    ]
