# Generated by Django 5.0.6 on 2024-07-09 18:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_videocomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='commented_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
