# Generated by Django 5.0.6 on 2024-09-01 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
