# Generated by Django 5.0.6 on 2024-09-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_mychats_delete_chatmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_expense', models.TextField()),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
