# Generated by Django 5.0.6 on 2024-09-07 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_expense_delete_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenshipVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship_card', models.ImageField(upload_to='citizenship_cards/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_request_sent', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
