# Generated by Django 5.0.6 on 2024-09-16 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mychats',
            name='chats',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='mychats',
            name='frnd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_friend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mychats',
            name='me',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
